/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package letiris;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author purpleside
 */
public class verEstoqueJFrame extends javax.swing.JFrame {

    private JFrame jframe;
    /**
     * Creates new form verEstoqueJFrame
     */
    public verEstoqueJFrame() {

        jframe = this;
        
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        String[] colunas = new String [] {"Código",
            "Nome",
            "Quantidade",
            "Preço Original",
            "Tipo", "Preço Final", "Lucro (%)"};
      


        ArrayList<Object[]> dados = Persistencia.getProdutos();
	


	SimpleTableModel modelo = new SimpleTableModel(dados, colunas);
	
	


        
       

        JTable table = new JTable(modelo);
        
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        

        JButton voltar_btn = new JButton("voltar");
        
        voltar_btn.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                    jframe.setVisible(false);
                    MenuFrame menu = new MenuFrame();
              
            }
        });
        
        JScrollPane scrollPane = new JScrollPane(table);
        this.add(scrollPane, BorderLayout.CENTER);
        this.add(voltar_btn, BorderLayout.SOUTH);
        this.setSize(600, 350);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        voltar.setLabel("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuFrame menu = new MenuFrame();
    }//GEN-LAST:event_voltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button voltar;
    // End of variables declaration//GEN-END:variables

    public class SimpleTableModel extends AbstractTableModel {

        private ArrayList linhas = null;
        private String[] colunas = null;

        public SimpleTableModel(ArrayList dados, String[] colunas) {
            this.linhas = dados;
            this.colunas = colunas;
        }

        public String[] getColunas() {
            return colunas;
        }

        public ArrayList getLinhas() {
            return linhas;
        }

        public void setColunas(String[] strings) {
            colunas = strings;
        }

        public void setLinhas(ArrayList list) {
            linhas = list;
        }

        /**
         * Retorna o numero de colunas no modelo
         *
         * @see javax.swing.table.TableModel#getColumnCount()
         */
        public int getColumnCount() {
            return getColunas().length;
        }

        /**
         * Retorna o numero de linhas existentes no modelo
         *
         * @see javax.swing.table.TableModel#getRowCount()
         */
        public int getRowCount() {
            return getLinhas().size();
        }

        /**
         * Obtem o valor na linha e coluna
         *
         * @see javax.swing.table.TableModel#getValueAt(int, int)
         */
        public Object getValueAt(int rowIndex, int columnIndex) {
            // Obtem a linha, que é uma String []
            Object[] linha = (Object[]) getLinhas().get(rowIndex);
            // Retorna o objeto que esta na coluna
            return linha[columnIndex];
        }

    }

}
